### ISSUE TITLE
Version of R

### ISSUE THREAD

**Issue by williamlai2** [tlorusso/traveltime#2]
Hi, this looks good. Are there plans to update this so that it will run on the latest version of R? I was running this on R version 3.4.? yesterday and it worked, but have updated to R version 3.5.2 and it is no longer possible to use this. Thanks.

**Comment by tlorusso** [comment]
Hi William, the package gets built successfully via travis with R version R 3.5.2. Some more specific info would be useful to understand what might cause the issue. Could you be more specific about the error you get and at what point you it is not possible to use it? Does the installation fail? Do you get an error when triggering the functions? Thanks  👍

**Comment by williamlai2** [comment]
Sorry, you are completely right. I was trying to install it via `install.packages("traveltime")` instead of via `devtools::install_github("tlorusso/traveltime")`.

**Comment by tlorusso** [comment]
No worries! Glad the package is being useful :) It's not on cran yet, i am planing to do some further improvements and will consider submitting a next version to cran. However, for now you have to install via github. Should you encounter issues when using the package or have suggestions regarding potential improvements, just let me know!
