### ISSUE TITLE
Coordinate not lie in a supported country

### ISSUE THREAD

**Issue by denironyx** [tlorusso/traveltime#3]
Hi @tlorusso,

This is a great work you have done with the {traveltime} package. 

I am trying to create isochrone around a point of interest in Qatar and South Africa. It seems this location is not supported by the API you are created. 

Do you have any idea, how it can become supported or any tips?

Thanks!

**Comment by tlorusso** [comment]
Hi Dennis

Thanks for your feedback! I appreciate you like my package! It wraps the traveltime API, which covers the following countries at the moment:

https://docs.traveltimeplatform.com/overview/supported-countries

You could turn to them and ask if they're planing to extend their service to further countries, in that case that would affect the package directly.
